### ISSUE TITLE
Removing REAP-inserted comments?

### ISSUE THREAD

**Issue by bitwombat** [casey/reap.vim#1]
Hi Casey,

Congrats on this cool project! I hope it takes off.

A few questions, which I'm stuffing inside one "issue" because maybe they belong in the README.

1) In your demo video, you mention REAP knows to replace its own comments on the next run. This sounds like it should be able to remove all of them then?

2) Do you see REAP being more of a REPL replacement, or is there a use case of it being used on a source code file?

3) What's with the "Magnasanti" stuff?

**Comment by casey** [comment]
Hi Bit,

Thank you!

1. Do you ask because you'd like functionality to remove reap comments once you're done with them? I think that's reasonable. Reap comments contain a `#` followed by a non-breaking space `U+00A0`, which is how it's able to recognize them and replace them. So it would be pretty easy to write a command that stripped them from the current file.

2. I think it's more of a REPL replacement, mostly because it only evaluates snippets with no regard for context, which means getting it to work on real source code which probably has dependencies will be very hard. I'd certainly be open to it, but since every python project has its own structure

3. I'm a huge fan and just kind of wanted to meme it out there.

https://www.youtube.com/watch?v=NTJQTc-TqpU
https://www.vice.com/en_us/article/4w4kg3/the-totalitarian-buddhist-who-beat-sim-city
https://youtu.be/ZjlegEk2IoQ

**Comment by bitwombat** [comment]
> Do you ask because you'd like functionality to remove reap comments once you're done with them?

Yes. And the U+00A0 marker makes it pretty easy to do with a decent editor... cool!

 > getting it to work on real source code which probably has dependencies will be very hard

Ah, so it's not running all the code and breakpointing or something...

Off to watch "Magnasanti" videos!
